name: Test Cert Manager

on: push

jobs:
  test:
    name : Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Go actions
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Test Go application
        run: make test

  generate-docs:
    runs-on: ubuntu-latest
    name: Generate documentation
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Generate GoDoc
        uses: ktr0731/godoc-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
